/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlytrungtamanhngu;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class GiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDien
     */
    Color DefaultColor, ClickedColor;
    public GiaoDien() {
        initComponents();
        DefaultColor = new Color(0,255,51);
        ClickedColor = new Color(255,153,153);
        
        
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(DefaultColor);
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor); 
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        HocVien1 = new javax.swing.JPanel();
        HocVien = new javax.swing.JLabel();
        Lop1 = new javax.swing.JPanel();
        jlbLop1 = new javax.swing.JLabel();
        ThiXetLop1 = new javax.swing.JPanel();
        jlbThiXetLop1 = new javax.swing.JLabel();
        HoaDon1 = new javax.swing.JPanel();
        jlbHoaDon1 = new javax.swing.JLabel();
        HocPhi1 = new javax.swing.JPanel();
        jlbHocPhi1 = new javax.swing.JLabel();
        BaoCaoKetQuaThi1 = new javax.swing.JPanel();
        jlbBaoCaoKetQuaThi1 = new javax.swing.JLabel();
        BaoCaoThongKeHoaDon1 = new javax.swing.JPanel();
        jlbBaoCaoThongKeHoaDon1 = new javax.swing.JLabel();
        BaoCaoThongKeHocPhi1 = new javax.swing.JPanel();
        jlbBaoCaoThongKeHocPhi1 = new javax.swing.JLabel();
        DiemDanh1 = new javax.swing.JPanel();
        jlbDiemDanh1 = new javax.swing.JLabel();
        Thoat = new javax.swing.JPanel();
        jlbBaoCaoThongKeHocPhi2 = new javax.swing.JLabel();
        GiangVien = new javax.swing.JPanel();
        jlbGiangVien1 = new javax.swing.JLabel();
        jDesktopPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setText("HỆ THỐNG QUẢN LÝ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        HocVien1.setBackground(new java.awt.Color(0, 255, 51));
        HocVien1.setPreferredSize(new java.awt.Dimension(0, 34));
        HocVien1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HocVien1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HocVien1MousePressed(evt);
            }
        });
        HocVien1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HocVien1KeyPressed(evt);
            }
        });

        HocVien.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        HocVien.setText("HỌC VIÊN");
        HocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HocVienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HocVien1Layout = new javax.swing.GroupLayout(HocVien1);
        HocVien1.setLayout(HocVien1Layout);
        HocVien1Layout.setHorizontalGroup(
            HocVien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HocVien1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HocVien)
                .addGap(100, 100, 100))
        );
        HocVien1Layout.setVerticalGroup(
            HocVien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HocVien1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HocVien, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        Lop1.setBackground(new java.awt.Color(51, 255, 51));
        Lop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lop1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lop1MousePressed(evt);
            }
        });

        jlbLop1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbLop1.setText("LỚP");

        javax.swing.GroupLayout Lop1Layout = new javax.swing.GroupLayout(Lop1);
        Lop1.setLayout(Lop1Layout);
        Lop1Layout.setHorizontalGroup(
            Lop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lop1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbLop1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        Lop1Layout.setVerticalGroup(
            Lop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lop1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbLop1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        ThiXetLop1.setBackground(new java.awt.Color(51, 255, 51));
        ThiXetLop1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThiXetLop1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThiXetLop1MousePressed(evt);
            }
        });

        jlbThiXetLop1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbThiXetLop1.setText(" THI XÉT LỚP");

        javax.swing.GroupLayout ThiXetLop1Layout = new javax.swing.GroupLayout(ThiXetLop1);
        ThiXetLop1.setLayout(ThiXetLop1Layout);
        ThiXetLop1Layout.setHorizontalGroup(
            ThiXetLop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThiXetLop1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jlbThiXetLop1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThiXetLop1Layout.setVerticalGroup(
            ThiXetLop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThiXetLop1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThiXetLop1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        HoaDon1.setBackground(new java.awt.Color(51, 255, 51));
        HoaDon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDon1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoaDon1MousePressed(evt);
            }
        });

        jlbHoaDon1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbHoaDon1.setText("HÓA ĐƠN");

        javax.swing.GroupLayout HoaDon1Layout = new javax.swing.GroupLayout(HoaDon1);
        HoaDon1.setLayout(HoaDon1Layout);
        HoaDon1Layout.setHorizontalGroup(
            HoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDon1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jlbHoaDon1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HoaDon1Layout.setVerticalGroup(
            HoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDon1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        HocPhi1.setBackground(new java.awt.Color(51, 255, 51));
        HocPhi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HocPhi1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HocPhi1MousePressed(evt);
            }
        });

        jlbHocPhi1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbHocPhi1.setText("HỌC PHÍ");

        javax.swing.GroupLayout HocPhi1Layout = new javax.swing.GroupLayout(HocPhi1);
        HocPhi1.setLayout(HocPhi1Layout);
        HocPhi1Layout.setHorizontalGroup(
            HocPhi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HocPhi1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbHocPhi1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        HocPhi1Layout.setVerticalGroup(
            HocPhi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HocPhi1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHocPhi1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        BaoCaoKetQuaThi1.setBackground(new java.awt.Color(51, 255, 51));
        BaoCaoKetQuaThi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaoCaoKetQuaThi1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BaoCaoKetQuaThi1MousePressed(evt);
            }
        });

        jlbBaoCaoKetQuaThi1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbBaoCaoKetQuaThi1.setText("BÁO CÁO KẾT QUẢ THI");

        javax.swing.GroupLayout BaoCaoKetQuaThi1Layout = new javax.swing.GroupLayout(BaoCaoKetQuaThi1);
        BaoCaoKetQuaThi1.setLayout(BaoCaoKetQuaThi1Layout);
        BaoCaoKetQuaThi1Layout.setHorizontalGroup(
            BaoCaoKetQuaThi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaoCaoKetQuaThi1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbBaoCaoKetQuaThi1)
                .addGap(62, 62, 62))
        );
        BaoCaoKetQuaThi1Layout.setVerticalGroup(
            BaoCaoKetQuaThi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaoCaoKetQuaThi1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBaoCaoKetQuaThi1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        BaoCaoThongKeHoaDon1.setBackground(new java.awt.Color(51, 255, 51));
        BaoCaoThongKeHoaDon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaoCaoThongKeHoaDon1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BaoCaoThongKeHoaDon1MousePressed(evt);
            }
        });

        jlbBaoCaoThongKeHoaDon1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbBaoCaoThongKeHoaDon1.setText("BÁO CÁO & THỐNG KÊ HÓA ĐƠN");

        javax.swing.GroupLayout BaoCaoThongKeHoaDon1Layout = new javax.swing.GroupLayout(BaoCaoThongKeHoaDon1);
        BaoCaoThongKeHoaDon1.setLayout(BaoCaoThongKeHoaDon1Layout);
        BaoCaoThongKeHoaDon1Layout.setHorizontalGroup(
            BaoCaoThongKeHoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaoCaoThongKeHoaDon1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbBaoCaoThongKeHoaDon1)
                .addGap(25, 25, 25))
        );
        BaoCaoThongKeHoaDon1Layout.setVerticalGroup(
            BaoCaoThongKeHoaDon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaoCaoThongKeHoaDon1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBaoCaoThongKeHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        BaoCaoThongKeHocPhi1.setBackground(new java.awt.Color(51, 255, 51));
        BaoCaoThongKeHocPhi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaoCaoThongKeHocPhi1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BaoCaoThongKeHocPhi1MousePressed(evt);
            }
        });

        jlbBaoCaoThongKeHocPhi1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbBaoCaoThongKeHocPhi1.setText("BÁO CÁO & THỐNG KÊ HỌC PHÍ");

        javax.swing.GroupLayout BaoCaoThongKeHocPhi1Layout = new javax.swing.GroupLayout(BaoCaoThongKeHocPhi1);
        BaoCaoThongKeHocPhi1.setLayout(BaoCaoThongKeHocPhi1Layout);
        BaoCaoThongKeHocPhi1Layout.setHorizontalGroup(
            BaoCaoThongKeHocPhi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaoCaoThongKeHocPhi1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbBaoCaoThongKeHocPhi1)
                .addGap(32, 32, 32))
        );
        BaoCaoThongKeHocPhi1Layout.setVerticalGroup(
            BaoCaoThongKeHocPhi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaoCaoThongKeHocPhi1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbBaoCaoThongKeHocPhi1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        DiemDanh1.setBackground(new java.awt.Color(51, 255, 51));
        DiemDanh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiemDanh1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DiemDanh1MousePressed(evt);
            }
        });

        jlbDiemDanh1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbDiemDanh1.setText("XẾP LỚP");

        javax.swing.GroupLayout DiemDanh1Layout = new javax.swing.GroupLayout(DiemDanh1);
        DiemDanh1.setLayout(DiemDanh1Layout);
        DiemDanh1Layout.setHorizontalGroup(
            DiemDanh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiemDanh1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbDiemDanh1)
                .addGap(103, 103, 103))
        );
        DiemDanh1Layout.setVerticalGroup(
            DiemDanh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiemDanh1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDiemDanh1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        Thoat.setBackground(new java.awt.Color(255, 153, 153));
        Thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThoatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ThoatMousePressed(evt);
            }
        });

        jlbBaoCaoThongKeHocPhi2.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jlbBaoCaoThongKeHocPhi2.setText("THOÁT ");

        javax.swing.GroupLayout ThoatLayout = new javax.swing.GroupLayout(Thoat);
        Thoat.setLayout(ThoatLayout);
        ThoatLayout.setHorizontalGroup(
            ThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThoatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbBaoCaoThongKeHocPhi2)
                .addGap(91, 91, 91))
        );
        ThoatLayout.setVerticalGroup(
            ThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbBaoCaoThongKeHocPhi2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
        );

        GiangVien.setBackground(new java.awt.Color(51, 255, 51));
        GiangVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GiangVienMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GiangVienMousePressed(evt);
            }
        });

        jlbGiangVien1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlbGiangVien1.setText("GIẢNG VIÊN");

        javax.swing.GroupLayout GiangVienLayout = new javax.swing.GroupLayout(GiangVien);
        GiangVien.setLayout(GiangVienLayout);
        GiangVienLayout.setHorizontalGroup(
            GiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GiangVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbGiangVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        GiangVienLayout.setVerticalGroup(
            GiangVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GiangVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbGiangVien1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HocVien1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
            .addComponent(Lop1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ThiXetLop1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DiemDanh1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HoaDon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HocPhi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BaoCaoKetQuaThi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BaoCaoThongKeHoaDon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BaoCaoThongKeHocPhi1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Thoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(GiangVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HocVien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThiXetLop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DiemDanh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HocPhi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BaoCaoKetQuaThi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BaoCaoThongKeHoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BaoCaoThongKeHocPhi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HocVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HocVienMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HocVienMouseClicked

    private void HocVien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HocVien1MouseClicked
        // TODO add your handling code here:
       HocVien hocvien = new HocVien();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(hocvien).setVisible(true);
    }//GEN-LAST:event_HocVien1MouseClicked

    private void HocVien1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HocVien1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HocVien1KeyPressed

    private void HocVien1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HocVien1MousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(ClickedColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(DefaultColor);  
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor); 
    }//GEN-LAST:event_HocVien1MousePressed

    private void Lop1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lop1MousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(ClickedColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(DefaultColor);
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor); 
    }//GEN-LAST:event_Lop1MousePressed

    private void ThiXetLop1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThiXetLop1MousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(ClickedColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(DefaultColor);  
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor);  
    }//GEN-LAST:event_ThiXetLop1MousePressed

    private void DiemDanh1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiemDanh1MousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(ClickedColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(DefaultColor);
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor);  
    }//GEN-LAST:event_DiemDanh1MousePressed

    private void HoaDon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDon1MousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(ClickedColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(DefaultColor);   
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor);  
    }//GEN-LAST:event_HoaDon1MousePressed

    private void HocPhi1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HocPhi1MousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(ClickedColor);
        GiangVien.setBackground(DefaultColor);      
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor);  
    }//GEN-LAST:event_HocPhi1MousePressed

    private void BaoCaoKetQuaThi1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoKetQuaThi1MousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(DefaultColor);  
        BaoCaoKetQuaThi1.setBackground(ClickedColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor);  
    }//GEN-LAST:event_BaoCaoKetQuaThi1MousePressed

    private void BaoCaoThongKeHoaDon1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoThongKeHoaDon1MousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(DefaultColor);
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(ClickedColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor);  
    }//GEN-LAST:event_BaoCaoThongKeHoaDon1MousePressed

    private void BaoCaoThongKeHocPhi1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoThongKeHocPhi1MousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(DefaultColor);
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(ClickedColor);  
    }//GEN-LAST:event_BaoCaoThongKeHocPhi1MousePressed

    private void Lop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lop1MouseClicked
        // TODO add your handling code here:
       Lop lop = new Lop();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(lop).setVisible(true); 
    }//GEN-LAST:event_Lop1MouseClicked

    private void ThiXetLop1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThiXetLop1MouseClicked
        // TODO add your handling code here:
       ThiXetLop thixetlop = new ThiXetLop();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(thixetlop).setVisible(true);  
    }//GEN-LAST:event_ThiXetLop1MouseClicked

    private void DiemDanh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiemDanh1MouseClicked
        // TODO add your handling code here:
       DiemDanh diemdanh = new DiemDanh();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(diemdanh).setVisible(true);    
    }//GEN-LAST:event_DiemDanh1MouseClicked

    private void HoaDon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDon1MouseClicked
        // TODO add your handling code here:
       HoaDon hoadon = new HoaDon();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(hoadon).setVisible(true);    
    }//GEN-LAST:event_HoaDon1MouseClicked

    private void HocPhi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HocPhi1MouseClicked
        // TODO add your handling code here:
       HocPhi hocphi = new HocPhi();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(hocphi).setVisible(true);    
    }//GEN-LAST:event_HocPhi1MouseClicked

    private void BaoCaoKetQuaThi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoKetQuaThi1MouseClicked
        // TODO add your handling code here:
       BaoCaoKetQuaThi baocaoketquatthi = new BaoCaoKetQuaThi();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(baocaoketquatthi).setVisible(true);  
    }//GEN-LAST:event_BaoCaoKetQuaThi1MouseClicked

    private void BaoCaoThongKeHoaDon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoThongKeHoaDon1MouseClicked
        // TODO add your handling code here:
       BaoCaoThongKeHoaDon baocaothongkehoadon = new BaoCaoThongKeHoaDon();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(baocaothongkehoadon).setVisible(true);   
    }//GEN-LAST:event_BaoCaoThongKeHoaDon1MouseClicked

    private void BaoCaoThongKeHocPhi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoThongKeHocPhi1MouseClicked
        // TODO add your handling code here:
       BaoCaoThongKeHocPhi baocaothongkehocphi= new BaoCaoThongKeHocPhi();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(baocaothongkehocphi).setVisible(true);  
    }//GEN-LAST:event_BaoCaoThongKeHocPhi1MouseClicked

    private void ThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThoatMouseClicked
        // TODO add your handling code here:
         if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không ?") == JOptionPane.NO_OPTION) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_ThoatMouseClicked

    private void ThoatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThoatMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThoatMousePressed

    private void GiangVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GiangVienMouseClicked
        // TODO add your handling code here:
       GiangVien giangvien = new GiangVien();
       jDesktopPanel.removeAll();
       jDesktopPanel.add(giangvien).setVisible(true); 
    }//GEN-LAST:event_GiangVienMouseClicked

    private void GiangVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GiangVienMousePressed
        // TODO add your handling code here:
        HocVien1.setBackground(DefaultColor);
        Lop1.setBackground(DefaultColor);
        ThiXetLop1.setBackground(DefaultColor);
        DiemDanh1.setBackground(DefaultColor);
        HoaDon1.setBackground(DefaultColor);
        HocPhi1.setBackground(DefaultColor);
        GiangVien.setBackground(ClickedColor);      
        BaoCaoKetQuaThi1.setBackground(DefaultColor);
        BaoCaoThongKeHoaDon1.setBackground(DefaultColor);
        BaoCaoThongKeHocPhi1.setBackground(DefaultColor);  
    }//GEN-LAST:event_GiangVienMousePressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BaoCaoKetQuaThi1;
    private javax.swing.JPanel BaoCaoThongKeHoaDon1;
    private javax.swing.JPanel BaoCaoThongKeHocPhi1;
    private javax.swing.JPanel DiemDanh1;
    private javax.swing.JPanel GiangVien;
    private javax.swing.JPanel HoaDon1;
    private javax.swing.JPanel HocPhi1;
    private javax.swing.JLabel HocVien;
    private javax.swing.JPanel HocVien1;
    private javax.swing.JPanel Lop1;
    private javax.swing.JPanel ThiXetLop1;
    private javax.swing.JPanel Thoat;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbBaoCaoKetQuaThi1;
    private javax.swing.JLabel jlbBaoCaoThongKeHoaDon1;
    private javax.swing.JLabel jlbBaoCaoThongKeHocPhi1;
    private javax.swing.JLabel jlbBaoCaoThongKeHocPhi2;
    private javax.swing.JLabel jlbDiemDanh1;
    private javax.swing.JLabel jlbGiangVien1;
    private javax.swing.JLabel jlbHoaDon1;
    private javax.swing.JLabel jlbHocPhi1;
    private javax.swing.JLabel jlbLop1;
    private javax.swing.JLabel jlbThiXetLop1;
    // End of variables declaration//GEN-END:variables
}
