/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlytrungtamanhngu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class HocPhi extends javax.swing.JInternalFrame {
    private int index;

    public Connection conn;
    public PreparedStatement ps;
    public ResultSet rs;
    DefaultTableModel tableModel;
    /**
     * Creates new form HocPhi
     */
    public HocPhi() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        tableModel = (DefaultTableModel) jtableHocPhi.getModel();
        jtxtSoTienPhaiDong.grabFocus();
        hienThiDuLieu();
    }
     private Connection ConnectToServer() {
        String user = "sa";
        String pass = "123456";
        try {
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=quanlytrungtamanhngu",user,pass);
            return conn;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return conn;
    }

    public void hienThiDuLieu() {
        try {
            conn = ConnectToServer();
            String sql = "select *"+
                            "from HOCPHI";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();

            //
            tableModel.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                  
                   };
                tableModel.addRow(row);
            }

            // 
            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public void refresh() {      
        jtxtMaHocPhi.setText("");
        jtxtMaHocVien.setText("");
        jtxtHanDongHocPhi.setText("");
        jtxtSoTienPhaiDong.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableHocPhi = new javax.swing.JTable();
        jtxtMaHocPhi = new javax.swing.JTextField();
        jtxtMaHocVien = new javax.swing.JTextField();
        jtxtHanDongHocPhi = new javax.swing.JTextField();
        jtxtSoTienPhaiDong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnThem = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();
        jbtnSua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxtTimKiem = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(659, 580));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ HỌC PHÍ");

        jtableHocPhi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Học Phí", " Mã Học Viên", "Số Tiền Phải Đóng", "Hạn Đóng Học Phí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtableHocPhi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableHocPhiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableHocPhi);

        jLabel2.setText("Mã Học Phí");

        jLabel3.setText("Số Tiền Phải Đóng");

        jLabel4.setText("Hạn Đóng Học Phí");

        jLabel5.setText("Mã Học Viên");

        jbtnThem.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbtnThem.setText("Thêm");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jbtnXoa.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbtnXoa.setText("Xóa ");
        jbtnXoa.setPreferredSize(new java.awt.Dimension(60, 28));
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        jbtnSua.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbtnSua.setText("Sửa");
        jbtnSua.setPreferredSize(new java.awt.Dimension(60, 28));
        jbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaActionPerformed(evt);
            }
        });

        jLabel6.setText("Tìm Kiếm");

        jtxtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jbtnThem)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtxtSoTienPhaiDong, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtxtHanDongHocPhi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                        .addComponent(jtxtMaHocVien, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtxtMaHocPhi, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel6)
                                .addGap(43, 43, 43)
                                .addComponent(jtxtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(21, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jtxtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtHanDongHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSoTienPhaiDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThem)
                    .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
        // TODO add your handling code here:
        try {
            StringBuffer sb = new StringBuffer();
            Validation.check(jtxtSoTienPhaiDong, sb, "Số tiền phải đóng không được để trống");
            //Validation.check(jtxtSDT, sb, "Sđt không được để trống");

//            while (true) {
//                if (jtxtSDT.getText().trim().equals("")) {
//                    JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống");
//                    jtxtSDT.grabFocus();
//                    return;
//                } else if (jtxtSDT.getText().trim().length() > 11 || jtxtSDT.getText().trim().length() < 10) {
//                    JOptionPane.showMessageDialog(this, "SĐT chứa từ 10-11 số.");
//                    jtxtSDT.grabFocus();
//                    return;
//                } else if (!jtxtSDT.getText().trim().matches("0[1-9]{1}\\d{8,9}")) {
//                    JOptionPane.showMessageDialog(this, "SĐT chưa đúng định dạng.");
//                    jtxtSDT.grabFocus();
//                    return;
//                } else {
//                    break;
//                }
//            }

            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb.toString(), "Invalidation", JOptionPane.ERROR_MESSAGE);
                return;
            }
            //Thêm vào csdl
            conn = ConnectToServer();
            String sql =  "INSERT INTO HOCPHI (MAHOCPHI,MAHOCVIEN,HANDONGHOCPHI,SoTienPhaiDong)" + "VALUES(?,?,?,?)";
//            String sql =  "INSERT INTO HOADON (1,2,3,4,5,6,7)" + "VALUES(?,?,?,?,?,?,?)";

            ps = conn.prepareStatement(sql);
//            rs = ps.executeQuery();
//            tableModel.setRowCount(0);
//            while(rs.next()){
//                
//            String[]row  = new String[]{
//            rs.getString(1),
//            rs.getString(2), 
//            rs.getString(3),
//            rs.getString(4),
//            rs.getString(5),
//            };
//         }
            ps.setString(1,jtxtMaHocPhi.getText());
            ps.setString(2,jtxtMaHocVien.getText());
            ps.setString(3,jtxtHanDongHocPhi.getText());
            ps.setFloat(4,Float.parseFloat(jtxtSoTienPhaiDong.getText()));         
            ps.executeUpdate();
            hienThiDuLieu();
            
            JOptionPane.showMessageDialog(this, "Thêm học phí thành công");
            refresh();
//            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); 
        }
    }//GEN-LAST:event_jbtnThemActionPerformed

    private void jtableHocPhiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableHocPhiMouseClicked
        // TODO add your handling code here:
        try {
            int row = jtableHocPhi.getSelectedRow();

            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn vào dòng cần hiển thị");
                return;
            } else {
                jtxtMaHocPhi.setText(jtableHocPhi.getValueAt(row, 0).toString());
                jtxtMaHocVien.setText(jtableHocPhi.getValueAt(row, 1).toString());
                jtxtHanDongHocPhi.setText(jtableHocPhi.getValueAt(row, 3).toString());
                jtxtSoTienPhaiDong.setText(jtableHocPhi.getValueAt(row, 2).toString());           
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_jtableHocPhiMouseClicked

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        // TODO add your handling code here:
           int row = jtableHocPhi.getSelectedRow();
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa học phí này không ?") == JOptionPane.NO_OPTION) {
            return;
        }
         try {
            if (getIndex() >= 0){
                row = getIndex();
            }
//        try {
            String MaHoaDon = jtableHocPhi.getValueAt(row, 0).toString();
            conn = ConnectToServer();
            //Xóa tt csdl từ mã kh
            String sql = "  DELETE FROM HOCPHI WHERE MAHOCPHI = ? ";
            ps = conn.prepareStatement(sql);
            ps.setString(1, MaHoaDon);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Xóa học phí này thành công");
            hienThiDuLieu();
            refresh();
            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnXoaActionPerformed

    private void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật học phí này không ?") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            conn = ConnectToServer();
            int row =jtableHocPhi.getSelectedRow();
            //Câp nhật vào csdl , lấy từ mã KH
            String sql = "update  HOCPHI set MAHOCVIEN = ?, SoTienPhaiDong = ?, HANDONGHOCPHI = ?"
            +" where MAHOCPHI = ? ";
            ps = conn.prepareStatement(sql);

            ps.setString(5, jtxtMaHocPhi.getText());
            ps.setString(1, jtxtMaHocVien.getText());           
            ps.setString(2,jtxtMaHocVien.getText());
            ps.setFloat(3, Float.parseFloat(jtxtSoTienPhaiDong.getText()));
            ps.setString(4, jtxtHanDongHocPhi.getText());
               
           
           
            //ps.setString(4,dtmKH.getValueAt(row,0 ).toString());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Cập nhật học phí thành công");
            hienThiDuLieu();
            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnSuaActionPerformed

    
    private int getIndex() {
        return index;
    }

    private void setIndex(int index) {
        this.index = index;
    }
    
    
    private void jtxtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTimKiemKeyReleased
        // TODO add your handling code here:
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
//              String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlytrungtamanhngu", user, pass; 
//              Connection con = DriverManager.getConnection(url);
              conn = ConnectToServer();
              String sql = "Select *from [HocPhi] where [MaHocPhi] = ?";
              PreparedStatement pst = conn.prepareStatement(sql);
              pst.setString(1, jtxtTimKiem.getText());
              ResultSet rs = pst.executeQuery();
              
              String getIndex = "SELECT [MaHocPhi], ROW_NUMBER() OVER (ORDER BY MaHocPhi) AS [MaHocPhi]\n"
                                + "FROM [HocPhi]";
              PreparedStatement ps = conn.prepareStatement(getIndex);
              ResultSet rt = ps.executeQuery();
              
            if (rs.next()) {
                String setidhocphi = rs.getString(1);
                jtxtMaHocPhi.setText(setidhocphi);

                String setidhocvien = rs.getString(2);
                jtxtMaHocVien.setText(setidhocvien);

                String sethandonghocphi = rs.getString(3);
                jtxtHanDongHocPhi.setText(sethandonghocphi);

                String setsotienphaidong= rs.getString(4);
                jtxtSoTienPhaiDong.setText(setsotienphaidong);

            }
            
            int index = 0;
            while (rt.next()){                
                if (rt.getString(1).equalsIgnoreCase(jtxtMaHocPhi.getText())){
                    System.out.println(rt.getString(1) + " " + rt.getString(2));
                    index = Integer.parseInt(rt.getString(2));
                }
            }
            if (index >= 0) {
                setIndex(index - 1);
                System.out.println(index);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jtxtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JTable jtableHocPhi;
    private javax.swing.JTextField jtxtHanDongHocPhi;
    private javax.swing.JTextField jtxtMaHocPhi;
    private javax.swing.JTextField jtxtMaHocVien;
    private javax.swing.JTextField jtxtSoTienPhaiDong;
    private javax.swing.JTextField jtxtTimKiem;
    // End of variables declaration//GEN-END:variables
}
