/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlytrungtamanhngu;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import static quanlytrungtamanhngu.HocVien.parseDate;
/**
 *
 * @author HP
 */
public class Lop extends javax.swing.JInternalFrame {
    private int index;
    public Connection conn;
    public PreparedStatement ps;
    public ResultSet rs;
    DefaultTableModel tableModel;
    /**
     * Creates new form Lop
     */
    public Lop() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        tableModel = (DefaultTableModel) jtableLop.getModel();
        jtxtMaKhoaHoc.grabFocus();
        hienThiDuLieu();
      
    }

    private Connection ConnectToServer() {
        String user = "sa";
        String pass = "123456";
        try {
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=quanlytrungtamanhngu",user,pass);
            return conn;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return conn;
    }

    public void hienThiDuLieu() {
        try {
            conn = ConnectToServer();
            String sql = "select MaLop, MaKhoaHoc, TenLop ,NgayBatDau ,NgayKetThuc \n"+
                            "from LOP";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();

            //
            tableModel.setRowCount(0);

            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("MaLop"),
                    rs.getString("MaKhoaHoc"),
                    rs.getString("TenLop"),
                    rs.getString("NgayBatDau"),
                    rs.getString("NgayKetThuc"),
                   };
                tableModel.addRow(row);
            }

            // 
            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
        public void refresh() {      
        jtxtMaLop.setText("");
        jtxtMaKhoaHoc.setText("");
        jtxtTenLop.setText("");
        jtxtNgayBatDau.setText("");
        jtxtNgayKetThuc.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableLop = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jtxtMaLop = new javax.swing.JTextField();
        jtxtMaKhoaHoc = new javax.swing.JTextField();
        jtxtTenLop = new javax.swing.JTextField();
        jtxtNgayBatDau = new javax.swing.JTextField();
        jtxtNgayKetThuc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jbtnThem = new javax.swing.JButton();
        jbtnXoa = new javax.swing.JButton();
        jbtnSua = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxtTimKiem = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(659, 580));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ LỚP");

        jtableLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Lớp", "Mã Khóa Học", "Tên Lớp", "Ngày Bắt Đầu", "Ngày Kết Thúc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtableLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableLopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableLop);

        jLabel2.setText("Mã Lớp");

        jLabel3.setText("Mã Khóa Học");

        jLabel4.setText("Tên Lớp");

        jLabel5.setText("Ngày Bắt Đầu ");

        jLabel6.setText("Ngày Kết Thúc");

        jbtnThem.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbtnThem.setText("Thêm");
        jbtnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemActionPerformed(evt);
            }
        });

        jbtnXoa.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbtnXoa.setText("Xóa");
        jbtnXoa.setPreferredSize(new java.awt.Dimension(60, 28));
        jbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaActionPerformed(evt);
            }
        });

        jbtnSua.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jbtnSua.setText("Sửa");
        jbtnSua.setPreferredSize(new java.awt.Dimension(60, 28));
        jbtnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaActionPerformed(evt);
            }
        });

        jLabel7.setText("Tìm Kiếm");

        jtxtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtTimKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxtNgayBatDau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jtxtTenLop, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtMaKhoaHoc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtMaLop, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtNgayKetThuc))
                .addGap(51, 51, 51)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jtxtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnThem)
                        .addGap(114, 114, 114)
                        .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jtxtMaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jtxtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jtxtMaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtxtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnThem)
                    .addComponent(jbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemActionPerformed
        // TODO add your handling code here:
         try {
            StringBuffer sb = new StringBuffer();
            Validation.check(jtxtTenLop, sb, "Tên lớp không được để trống");
            //Validation.check(jtxtSDT, sb, "Sđt không được để trống");

//            while (true) {
//                if (jtxtSDT.getText().trim().equals("")) {
//                    JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống");
//                    jtxtSDT.grabFocus();
//                    return;
//                } else if (jtxtSDT.getText().trim().length() > 11 || jtxtSDT.getText().trim().length() < 10) {
//                    JOptionPane.showMessageDialog(this, "SĐT chứa từ 10-11 số.");
//                    jtxtSDT.grabFocus();
//                    return;
//                } else if (!jtxtSDT.getText().trim().matches("0[1-9]{1}\\d{8,9}")) {
//                    JOptionPane.showMessageDialog(this, "SĐT chưa đúng định dạng.");
//                    jtxtSDT.grabFocus();
//                    return;
//                } else {
//                    break;
//                }
//            }

            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb.toString(), "Invalidation", JOptionPane.ERROR_MESSAGE);
                return;
            }
            //Thêm vào csdl
            conn = ConnectToServer();
            String sql =  "INSERT INTO LOP (MALOP,MAKHOAHOC,TENLOP,NGAYBATDAU,NGAYKETTHUC)" + "VALUES(?,?,?,?,?)";
            ps = conn.prepareStatement(sql);
//            rs = ps.executeQuery();
//            tableModel.setRowCount(0);
//            while(rs.next()){
//                
//            String[]row  = new String[]{
//            rs.getString(1),
//            rs.getString(2), 
//            rs.getString(3),
//            rs.getString(4),
//            rs.getString(5),
//            };
//         }
            ps.setString(1,jtxtMaLop.getText());
            ps.setString(2,jtxtMaKhoaHoc.getText());
            ps.setString(3,jtxtTenLop.getText());
            ps.setString(4,jtxtNgayBatDau.getText());
            ps.setString(5,jtxtNgayKetThuc.getText());
            ps.executeUpdate();
            hienThiDuLieu();
            
            JOptionPane.showMessageDialog(this, "Thêm lớp thành công");
            refresh();
//            rs.close();
            ps.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jbtnThemActionPerformed

    private void jbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaActionPerformed
        // TODO add your handling code here:
         int row = jtableLop.getSelectedRow();
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa lớp học này không ?") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            if (getIndex() >= 0){
                row = getIndex();
            }
            
       // try {
            String MaLop = jtableLop.getValueAt(row, 0).toString();
            conn = ConnectToServer();
            //Xóa tt csdl từ mã kh
            String sql = "  DELETE FROM LOP WHERE MALOP = ? ";
            ps = conn.prepareStatement(sql);
            ps.setString(1, MaLop);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Xóa lớp học này thành công");
            hienThiDuLieu();
            refresh();
            rs.close();
            ps.close();
            conn.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jbtnXoaActionPerformed

    private void jtableLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableLopMouseClicked
        // TODO add your handling code here:
          try {
            int row = jtableLop.getSelectedRow();

            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn vào dòng cần hiển thị");
                return;
            } else {
                jtxtMaLop.setText(jtableLop.getValueAt(row, 0).toString());
                jtxtMaKhoaHoc.setText(jtableLop.getValueAt(row, 1).toString());
                jtxtTenLop.setText(jtableLop.getValueAt(row, 2).toString());
                jtxtNgayBatDau.setText(jtableLop.getValueAt(row, 3).toString());
                jtxtNgayKetThuc.setText(jtableLop.getValueAt(row, 4).toString());
             
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jtableLopMouseClicked

    private void jbtnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaActionPerformed
        // TODO add your handling code here:
        // String DATE_FORMAT = "YYYY-MM-DD";
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật lớp này không ?") == JOptionPane.NO_OPTION) {
            return;
        }
        try {
            conn = ConnectToServer();
            int row =jtableLop.getSelectedRow();
            //Câp nhật vào csdl , lấy từ mã KH
            String sql = "update  LOP set MAKHOAHOC = ?, TENLOP = ?,NGAYBATDAU = ?, NGAYKETTHUC = ?"
            +" where MALOP = ? ";
            ps = conn.prepareStatement(sql);

            ps.setString(5, jtxtMaLop.getText());
            ps.setString(1, jtxtMaKhoaHoc.getText());           
            ps.setString(2,jtxtTenLop.getText());
            ps.setString(3, jtxtNgayBatDau.getText());
            ps.setString(4, jtxtNgayKetThuc.getText());
           
           
            //ps.setString(4,dtmKH.getValueAt(row,0 ).toString());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Cập nhật lớp thành công");
            hienThiDuLieu();
            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jbtnSuaActionPerformed

     private int getIndex() {
        return index;
    }

    private void setIndex(int index) {
        this.index = index;
    }
    private void jtxtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtTimKiemKeyReleased
        // TODO add your handling code here:
      try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
//              String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlytrungtamanhngu", user, pass; 
//              Connection con = DriverManager.getConnection(url);
              conn = ConnectToServer();
              String sql = "Select *from [Lop] where [MaLop] = ?";
              PreparedStatement pst = conn.prepareStatement(sql);
              pst.setString(1, jtxtTimKiem.getText());
              ResultSet rs = pst.executeQuery();
              
              String getIndex = "SELECT [MaLop], ROW_NUMBER() OVER (ORDER BY MaLop) AS [MaLop]\n"
                                + "FROM [Lop]";
              PreparedStatement ps = conn.prepareStatement(getIndex);
              ResultSet rt = ps.executeQuery();
              
            if (rs.next()) {
                String setid = rs.getString(1);
                jtxtMaLop.setText(setid);

                String setkhoahoc = rs.getString(2);
                jtxtMaKhoaHoc.setText(setkhoahoc);

                String settenlop = rs.getString(3);
                jtxtTenLop.setText(settenlop);

                String setngaybatdau= rs.getString(4);
                jtxtNgayBatDau.setText(setngaybatdau);

                String setngayketthuc = rs.getString(5);
                jtxtNgayKetThuc.setText(setngayketthuc);
            }
            
            int index = 0;
            while (rt.next()){                
                if (rt.getString(1).equalsIgnoreCase(jtxtMaLop.getText())){
                    System.out.println(rt.getString(1) + " " + rt.getString(2));
                    index = Integer.parseInt(rt.getString(2));
                }
            }
            if (index >= 0) {
                setIndex(index - 1);
                System.out.println(index);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jtxtTimKiemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnSua;
    private javax.swing.JButton jbtnThem;
    private javax.swing.JButton jbtnXoa;
    private javax.swing.JTable jtableLop;
    private javax.swing.JTextField jtxtMaKhoaHoc;
    private javax.swing.JTextField jtxtMaLop;
    private javax.swing.JTextField jtxtNgayBatDau;
    private javax.swing.JTextField jtxtNgayKetThuc;
    private javax.swing.JTextField jtxtTenLop;
    private javax.swing.JTextField jtxtTimKiem;
    // End of variables declaration//GEN-END:variables
}
